2023-07-14 17:32:54,929 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(pages, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:33:13,709 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(pages, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:33:21,784 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(pages, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:33:44,181 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(pages, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:34:30,419 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(pages, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:34:36,174 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:48]
2023-07-14 17:34:40,765 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(pages, app.config['POSTS_PER_PAGE'], False)
NameError: name 'pages' is not defined
2023-07-14 17:34:43,781 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(pages, app.config['POSTS_PER_PAGE'], False)
NameError: name 'pages' is not defined
2023-07-14 17:35:05,634 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:48]
2023-07-14 17:50:12,212 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:50]
2023-07-15 00:27:28,885 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:50]
